/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'

// Create Virtual Routes

const ZenlessZoneZeroLazyImport = createFileRoute('/zenless-zone-zero')()
const StarRailLazyImport = createFileRoute('/star-rail')()
const GenshinImpactLazyImport = createFileRoute('/genshin-impact')()

// Create/Update Routes

const ZenlessZoneZeroLazyRoute = ZenlessZoneZeroLazyImport.update({
  id: '/zenless-zone-zero',
  path: '/zenless-zone-zero',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/zenless-zone-zero.lazy').then((d) => d.Route),
)

const StarRailLazyRoute = StarRailLazyImport.update({
  id: '/star-rail',
  path: '/star-rail',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/star-rail.lazy').then((d) => d.Route))

const GenshinImpactLazyRoute = GenshinImpactLazyImport.update({
  id: '/genshin-impact',
  path: '/genshin-impact',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/genshin-impact.lazy').then((d) => d.Route),
)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/genshin-impact': {
      id: '/genshin-impact'
      path: '/genshin-impact'
      fullPath: '/genshin-impact'
      preLoaderRoute: typeof GenshinImpactLazyImport
      parentRoute: typeof rootRoute
    }
    '/star-rail': {
      id: '/star-rail'
      path: '/star-rail'
      fullPath: '/star-rail'
      preLoaderRoute: typeof StarRailLazyImport
      parentRoute: typeof rootRoute
    }
    '/zenless-zone-zero': {
      id: '/zenless-zone-zero'
      path: '/zenless-zone-zero'
      fullPath: '/zenless-zone-zero'
      preLoaderRoute: typeof ZenlessZoneZeroLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/genshin-impact': typeof GenshinImpactLazyRoute
  '/star-rail': typeof StarRailLazyRoute
  '/zenless-zone-zero': typeof ZenlessZoneZeroLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/genshin-impact': typeof GenshinImpactLazyRoute
  '/star-rail': typeof StarRailLazyRoute
  '/zenless-zone-zero': typeof ZenlessZoneZeroLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/genshin-impact': typeof GenshinImpactLazyRoute
  '/star-rail': typeof StarRailLazyRoute
  '/zenless-zone-zero': typeof ZenlessZoneZeroLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/genshin-impact' | '/star-rail' | '/zenless-zone-zero'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/genshin-impact' | '/star-rail' | '/zenless-zone-zero'
  id: '__root__' | '/' | '/genshin-impact' | '/star-rail' | '/zenless-zone-zero'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenshinImpactLazyRoute: typeof GenshinImpactLazyRoute
  StarRailLazyRoute: typeof StarRailLazyRoute
  ZenlessZoneZeroLazyRoute: typeof ZenlessZoneZeroLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenshinImpactLazyRoute: GenshinImpactLazyRoute,
  StarRailLazyRoute: StarRailLazyRoute,
  ZenlessZoneZeroLazyRoute: ZenlessZoneZeroLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/genshin-impact",
        "/star-rail",
        "/zenless-zone-zero"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/genshin-impact": {
      "filePath": "genshin-impact.lazy.tsx"
    },
    "/star-rail": {
      "filePath": "star-rail.lazy.tsx"
    },
    "/zenless-zone-zero": {
      "filePath": "zenless-zone-zero.lazy.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
