/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as IndexIndexImport } from './routes/index/index'

// Create Virtual Routes

const ZenlessZoneZeroLazyImport = createFileRoute('/zenless-zone-zero')()
const HonkaiStarRailLazyImport = createFileRoute('/honkai-star-rail')()
const GenshinImpactLazyImport = createFileRoute('/genshin-impact')()

// Create/Update Routes

const ZenlessZoneZeroLazyRoute = ZenlessZoneZeroLazyImport.update({
  id: '/zenless-zone-zero',
  path: '/zenless-zone-zero',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/zenless-zone-zero.lazy').then((d) => d.Route),
)

const HonkaiStarRailLazyRoute = HonkaiStarRailLazyImport.update({
  id: '/honkai-star-rail',
  path: '/honkai-star-rail',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/honkai-star-rail.lazy').then((d) => d.Route),
)

const GenshinImpactLazyRoute = GenshinImpactLazyImport.update({
  id: '/genshin-impact',
  path: '/genshin-impact',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/genshin-impact.lazy').then((d) => d.Route),
)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const IndexIndexRoute = IndexIndexImport.update({
  id: '/index/',
  path: '/index/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/genshin-impact': {
      id: '/genshin-impact'
      path: '/genshin-impact'
      fullPath: '/genshin-impact'
      preLoaderRoute: typeof GenshinImpactLazyImport
      parentRoute: typeof rootRoute
    }
    '/honkai-star-rail': {
      id: '/honkai-star-rail'
      path: '/honkai-star-rail'
      fullPath: '/honkai-star-rail'
      preLoaderRoute: typeof HonkaiStarRailLazyImport
      parentRoute: typeof rootRoute
    }
    '/zenless-zone-zero': {
      id: '/zenless-zone-zero'
      path: '/zenless-zone-zero'
      fullPath: '/zenless-zone-zero'
      preLoaderRoute: typeof ZenlessZoneZeroLazyImport
      parentRoute: typeof rootRoute
    }
    '/index/': {
      id: '/index/'
      path: '/index'
      fullPath: '/index'
      preLoaderRoute: typeof IndexIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/genshin-impact': typeof GenshinImpactLazyRoute
  '/honkai-star-rail': typeof HonkaiStarRailLazyRoute
  '/zenless-zone-zero': typeof ZenlessZoneZeroLazyRoute
  '/index': typeof IndexIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/genshin-impact': typeof GenshinImpactLazyRoute
  '/honkai-star-rail': typeof HonkaiStarRailLazyRoute
  '/zenless-zone-zero': typeof ZenlessZoneZeroLazyRoute
  '/index': typeof IndexIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/genshin-impact': typeof GenshinImpactLazyRoute
  '/honkai-star-rail': typeof HonkaiStarRailLazyRoute
  '/zenless-zone-zero': typeof ZenlessZoneZeroLazyRoute
  '/index/': typeof IndexIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/genshin-impact'
    | '/honkai-star-rail'
    | '/zenless-zone-zero'
    | '/index'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/genshin-impact'
    | '/honkai-star-rail'
    | '/zenless-zone-zero'
    | '/index'
  id:
    | '__root__'
    | '/'
    | '/genshin-impact'
    | '/honkai-star-rail'
    | '/zenless-zone-zero'
    | '/index/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GenshinImpactLazyRoute: typeof GenshinImpactLazyRoute
  HonkaiStarRailLazyRoute: typeof HonkaiStarRailLazyRoute
  ZenlessZoneZeroLazyRoute: typeof ZenlessZoneZeroLazyRoute
  IndexIndexRoute: typeof IndexIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GenshinImpactLazyRoute: GenshinImpactLazyRoute,
  HonkaiStarRailLazyRoute: HonkaiStarRailLazyRoute,
  ZenlessZoneZeroLazyRoute: ZenlessZoneZeroLazyRoute,
  IndexIndexRoute: IndexIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/genshin-impact",
        "/honkai-star-rail",
        "/zenless-zone-zero",
        "/index/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/genshin-impact": {
      "filePath": "genshin-impact.lazy.tsx"
    },
    "/honkai-star-rail": {
      "filePath": "honkai-star-rail.lazy.tsx"
    },
    "/zenless-zone-zero": {
      "filePath": "zenless-zone-zero.lazy.tsx"
    },
    "/index/": {
      "filePath": "index/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
